### ISSUE TITLE
Neplatny podpis SOAP zpravy

### ISSUE THREAD

**Issue by mmisar** [limosek/eetcli#1]
Nefunfuje mi defaultní testovací režim EET, program končí chybou "Neplatny podpis SOAP zpravy".
```
/eetcli --trzba 15
Vracim vychozi uctenku, protoze je pouzity testovaci DIC.
Neprodukční prostředí. Pro produkční zadejte -p 0.
Neplatny podpis SOAP zpravy
```
Protože jsem se dočetl, že 2.6.2020 měnili playground klíče, zkusil jsem i stáhnout aktuální playground EET_CA1_Playground_v3.zip z https://www.etrzby.cz/cs/technicka-specifikace a nahradit použitý klíč v ./keys/ a přegenerovat klíče pomocí:
`make pem P12=keys/EET_CA1_Playground-CZ1212121218.p12 PASS=eet`
ty jsem z ./keys/ nakopíroval do ./bins/.keys/
bohužel i s novými klíči to končí stejnou chybou.
Prosím o zprovoznění.
použitý ini soubor je zde:
[eetcli.ini.txt](https://github.com/limosek/eetcli/files/4776385/eetcli.ini.txt)

**Comment by limosek** [comment]
Diky za report, problem byl opravdu ve starych klicich. Updatoval jsem klice z playgroundu a u mne vse funguje. Melo by byt opraveno v: https://github.com/limosek/eetcli/commit/2c10ecf410a550c29ea777410af441389971b184

Zkuste.

**Comment by mmisar** [comment]
Dobrý den,
u mě to stále nefunguje
```
./eetcli --debug 20 --trzba 15
Vracim vychozi uctenku, protoze je pouzity testovaci DIC.
Created tmp file ./EETXMLSchema.xsd from phar:///home/martin/programy/eet/new/eetcli/bin/eetcli/inc/../vendor/ondrejnov/eet/src/Schema/EETXMLSchema.xsd
Created tmp file ./PlaygroundService.wsdl from phar:///home/martin/programy/eet/new/eetcli/bin/eetcli/inc/../vendor/ondrejnov/eet/src/Schema/PlaygroundService.wsdl
Neprodukční prostředí. Pro produkční zadejte -p 0.
WSDL: ./PlaygroundService.wsdl
Key: phar:///home/martin/programy/eet/new/eetcli/bin/eetcli/keys/EET_CA1_Playground-CZ1212121218.pem
Cert: phar:///home/martin/programy/eet/new/eetcli/bin/eetcli/keys/EET_CA1_Playground-CZ1212121218.crt
DIC: CZ1212121218
Adding macro uuid_zpravy=2ec90dde-ef0a-4636-adf5-c9cb6a7077de
Adding macro prvni_zaslani=1
Adding macro dic_popl=CZ1212121218
Adding macro dic_poverujiciho=
Adding macro id_provoz=1
Adding macro id_pokl=1
Adding macro porad_cis=1
Adding macro dat_trzby=18.06.2020 18:08
Adding macro celk_trzba=15
Adding macro zakl_nepodl_dph=0
Adding macro zakl_dan1=0
Adding macro dan1=0
Adding macro zakl_dan2=0
Adding macro dan2=0
Adding macro zakl_dan3=0
Adding macro dan3=0
Adding macro cest_sluz=0
Adding macro pouzit_zboz1=0
Adding macro pouzit_zboz2=0
Adding macro pouzit_zboz3=0
Adding macro urceno_cerp_zuct=0
Adding macro cerp_zuct=0
Adding macro rezim=0
Zasilam uctenku na etrzby: 
Neplatny podpis SOAP zpravy
Deleting tmp file ./EETXMLSchema.xsd
Deleting tmp file ./PlaygroundService.wsdl
```
verze by měla být OK
(kousek z git log)
```
commit 2c10ecf410a550c29ea777410af441389971b184 (HEAD -> master, origin/master, origin/HEAD)
Author: Lukas Macura <lukas@macura.cz>
Date:   Mon Jun 15 12:57:28 2020 +0200

    Added all testing keys

commit 5b1c3d5de445df7f7a3aeb4747555159f1ce8fc1
Author: Lukas Macura <lukas@macura.cz>
Date:   Mon Jun 15 12:55:37 2020 +0200

    Updated playground keys
```
čím by to mohlo být (moje distribuce je archlinux)?

**Comment by limosek** [comment]
eetcli v adresari bin je "compilovana" verze a asi obsahovala stare klice.
Pushnul jsem novou verzi kompilovaneho eetcli. Zkuste git pull.

Udelejte

git reset --hard
make distclean
composer update
make

pokud nefunguje kompilovana verze, tak ta textova by mela fungovat.

php eetcli.php --trzba 15

**Comment by mmisar** [comment]
Děkuji moc, už to funguje. 
Nechtělo se mi před tím doinstalovávat závislosti, tak jsem zkoušel jen kompilovanou verzi.

**Comment by limosek** [comment]
Diky za reporting!
